name: Build CLI linux arm64

on:
  push:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-22.04-arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: |-
          cd nyalcf_cli
          dart pub get
          cd ..

      - name: Compile CLI
        run: |-
          cd nyalcf_cli
          mkdir -p build
          dart compile exe bin/nyalcf_cli.dart -o build/nyalcf_cli-linux-arm64
          cd ..

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux ARM64 Artifact
          path: nyalcf_cli/build
          