name: Sort Imports

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sort-imports:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Make script executable
      run: chmod +x ./sort-import.sh

    - name: Run sort-import.sh
      run: ./sort-import.sh